config/routes.rb
Rails.application.routes.draw do
  resources :tets do
  	collection do
  		get 'commit'
  	end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tet.rb
class Tet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tets_controller.rb
class TetsController < ApplicationController
  require 'git'
  before_action :config_git
  before_action :read_git
  def index
    
  end

  def config_git
    Git.configure do |config|

    # If you need to use a custom SSH script
    config.git_ssh = 'git@github.com:huylong12/mama.git'
    end
  end

  def commit
    
  end

  def read_git
     
    g = Git.open(working_dir = '\Sites\xxx', :log => Logger.new(STDOUT))

    g.add('app/assets/javascripts/application.js')
    debugger
    g.commit('dsadashkjkghdasdas')
    # g.branch('new_branch11').checkout
    # debugger
    # g.pull
    g.push
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tets_helper.rb
module TetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xxx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tets/_form.html.erb
<%= form_with(model: tet, local: true) do |form| %>
  <% if tet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tet.errors.count, "error") %> prohibited this tet from being saved:</h2>

      <ul>
      <% tet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :tet_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tets/edit.html.erb
<h1>Editing Tet</h1>

<%= render 'form', tet: @tet %>

<%= link_to 'Show', @tet %> |
<%= link_to 'Back', tets_path %>

app/views/tets/html.html.erb
fds

app/views/tets/index.html.erb
<%= link_to( 'Open Popup-Window', tets_path, 'data-popup' => true ) %>

app/views/tets/new.html.erb
<h1>New Tet</h1>

<%= render 'form', tet: @tet %>

<%= link_to 'Back', tets_path %>

app/views/tets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tet.name %>
</p>

<%= link_to 'Edit', edit_tet_path(@tet) %> |
<%= link_to 'Back', tets_path %>